### ISSUE TITLE
Unsupported upload of multiple files

### ISSUE THREAD

**Issue by mamillastre** [chadicus/slim-oauth2-http#47]
Hello,
The "convertUploadedFiles" method in the RequestBridge class doesn't support the multiple files uploaded with a same key, as described in the Slim documentation (https://www.slimframework.com/docs/v3/cookbook/uploading-files.html).

## Expected Behavior
The multiple files in one input or the multiple inputs with the same key are fully supported by the RequestBridge.

## Actual Behavior
Only one file can be uploaded in an input with a unique key.

## Steps to reproduce the behavior
Send multiple files using an input named "name[]" in a post request.
The following error must appear: 
`Error: Call to a member function getClientFilename() on array`

Thank you.

**Comment by chadicus** [comment]
@renji31 this should be fixed with v3.1.7
